configuration: 
  name: treckba-corpus
  author: ziy
  
persistence-provider:
  inherit: treckba-corpus.persistence.local-persistence-provider

collection-reader:
  inherit: treckba-corpus.collection.thrift-dir-reader
  
pipeline:
  - inherit: ecd.phase
    name: filter
    options: |
      - inherit: treckba-corpus.filter.expanded-keyterms

  - inherit: treckba-corpus.eval.trace-evaluator-aggregator
  
  - inherit: treckba-corpus.index.lucene

post-process:
  - inherit: jdbc.eval.retrieval-evaluator-consumer

  - inherit: report.csv-report-generator
    builders: |
      - inherit: jdbc.report.f-measure-report-component