configuration: 
  name: treckba-corpus
  author: ziy
  
persistence-provider:
  inherit: treckba-corpus.persistence.local-persistence-provider

collection-reader:
  inherit: treckba-corpus.collection.thrift-dir-reader
  
pipeline:
  - inherit: ecd.phase
    name: filter
    options: |
      - inherit: treckba-corpus.filter.expanded-keyterms

  - inherit: treckba-corpus.index.lucene
